server {
    listen 80;
    server_name _;

    # 1. Configuración para las IMÁGENES (Uploads)
    location /uploads/ {
        alias /data/uploads/;
        add_header Access-Control-Allow-Origin *;
        autoindex off;
    }

   # 2. Configuración para BACKEND (API, Swagger y H2)
location ~ ^/(api|swagger-ui|v3/api-docs|h2-console) {
    proxy_pass http://spring-api:8080;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_hide_header X-Frame-Options; 
    add_header X-Frame-Options "SAMEORIGIN";
}

    # 3. Configuración para el FRONTEND ADMINISTRADOR (Angular)
    location /admin {
        proxy_pass http://angular-admin:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # 4. Configuración para el FRONTEND (React)
    location / {
        proxy_pass http://react-web:80; 
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}