-- Configuración de tablas para BLUECREW (Compatible con H2 y MySQL)

CREATE TABLE USUARIOS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ROL ENUM('ADMIN', 'USER') DEFAULT 'USER',
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    CREAR_EVENTO BOOLEAN DEFAULT FALSE,
    NOMBRE VARCHAR(100) NOT NULL,
    APELLIDO VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    BIOGRAFIA VARCHAR(500),
    FOTO VARCHAR(100),
    LOCALIDAD VARCHAR(100),
    ACTIVO BOOLEAN DEFAULT TRUE,
    EVENTOS_COMPLETADOS INT NOT NULL DEFAULT 0,
    CREADO_EN TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ACTUALIZADO_EN TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ORGANIZACIONES (
    ID_ORGANIZACION INT AUTO_INCREMENT PRIMARY KEY,
    ID_APROBADO_POR INT NULL,
    NOMBRE_ORGANIZACION VARCHAR(100) NOT NULL,
    DESCRIPCION VARCHAR(500) NOT NULL,
    SITIO_WEB VARCHAR(100),
    LOGO VARCHAR(100),
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    LOCALIDAD VARCHAR(100),
    TELEFONO VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    ESTADO_APROBACION ENUM('PENDIENTE', 'APROBADO', 'RECHAZADO') DEFAULT 'PENDIENTE',
    FECHA_APROBACION TIMESTAMP,
    FOREIGN KEY (ID_APROBADO_POR) REFERENCES USUARIOS (ID)
);

CREATE TABLE CATEGORIAS (
    ID_CATEGORIA INT AUTO_INCREMENT PRIMARY KEY,
    ID_CREADOR INT NOT NULL,
    NOMBRE_CATEGORIA VARCHAR(100) NOT NULL,
    DESCRIPCION VARCHAR(500) NOT NULL,
    APROBADO BOOLEAN DEFAULT FALSE,
    FECHA_CREACION TIMESTAMP NOT NULL,
    FECHA_APROBACION TIMESTAMP,
    FOREIGN KEY (ID_CREADOR) REFERENCES USUARIOS (ID)
);

CREATE TABLE EVENTOS (
    ID_EVENTO INT AUTO_INCREMENT PRIMARY KEY,
    ID_CATEGORIA INT NOT NULL,
    ID_USER INT,
    ID_ORGANIZACION INT,
    TITULO VARCHAR(100) NOT NULL,
    DESCRIPCION VARCHAR(500) NOT NULL,
    IMAGEN VARCHAR(100),
    FECHA_INICIO TIMESTAMP NOT NULL,
    FECHA_FIN TIMESTAMP NOT NULL,
    FECHA_PUBLICACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UBICACION VARCHAR(100) NOT NULL,
    ESTADO ENUM('PENDIENTE', 'APROBADO', 'RECHAZADO', 'CANCELADO', 'BORRADOR') DEFAULT 'PENDIENTE',
    PARTICIPANTES INT NOT NULL DEFAULT 5, 
    FINALIZADO BOOLEAN DEFAULT FALSE,
    MATERIAL_NECESARIO VARCHAR(500),
    FOREIGN KEY (ID_USER) REFERENCES USUARIOS (ID),
    FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIAS (ID_CATEGORIA),
    FOREIGN KEY (ID_ORGANIZACION) REFERENCES ORGANIZACIONES (ID_ORGANIZACION),
    CONSTRAINT CHK_Creador_Evento CHECK (
        (ID_USER IS NOT NULL AND ID_ORGANIZACION IS NULL) OR
        (ID_USER IS NULL AND ID_ORGANIZACION IS NOT NULL)
        )
);

CREATE TABLE NOTICIAS (
    ID_NOTICIA INT  AUTO_INCREMENT PRIMARY KEY,
    ID_AUTOR INT NOT NULL,
    ID_CATEGORIA INT NOT NULL,
    TITULO VARCHAR(100) NOT NULL,
    IMAGEN VARCHAR(100),
    DESCRIPCION TEXT,
    ESTADO_APROBACION_NOTICIA ENUM('PENDIENTE', 'APROBADO', 'RECHAZADO') DEFAULT 'PENDIENTE',
    FECHA_PUBLICACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ESTADO_VISIBILIDAD BOOLEAN DEFAULT TRUE,
    FOREIGN KEY (ID_AUTOR) REFERENCES USUARIOS (ID),
    CITA_DESTACADA VARCHAR(100),
    FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIAS (ID_CATEGORIA)
);

CREATE TABLE INSCRIPCIONES (
    ID_EVENTO INT NOT NULL,
    ID_USUARIO INT NOT NULL,
    FECHA_INSCRIPCION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ASISTIO BOOLEAN DEFAULT FALSE,
    PRIMARY KEY (ID_EVENTO, ID_USUARIO),
    FOREIGN KEY (ID_EVENTO) REFERENCES EVENTOS (ID_EVENTO),
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS (ID)
);

CREATE TABLE RECOLECCION_RESIDUOS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ID_EVENTO INT NOT NULL,
    CANTIDAD_RECOLECTADA DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY (ID_EVENTO) REFERENCES EVENTOS (ID_EVENTO)
);

CREATE TABLE CALIFICACIONES (
    ID_USUARIO INT NOT NULL,
    ID_EVENTO INT NOT NULL,
    CALIFICACION INT NOT NULL CHECK (CALIFICACION BETWEEN 1 AND 5),
    COMENTARIO VARCHAR(500),
    FECHA_CALIFICACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID_USUARIO, ID_EVENTO),
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS (ID),
    FOREIGN KEY (ID_EVENTO) REFERENCES EVENTOS (ID_EVENTO)
);


CREATE TABLE IF NOT EXISTS CONTACTOS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(255) NOT NULL,
    APELLIDOS VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    DIRECCION VARCHAR(255),
    ASUNTO VARCHAR(150),
    MENSAJE TEXT NOT NULL,
    ESTADO ENUM('PENDIENTE', 'RESPONDIDO', 'CERRADO') DEFAULT 'PENDIENTE',
    RESPUESTA TEXT,
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);